# --------------------------
# FEATURE MAP DATASETS ROOTS
# --------------------------

#gcd_feature_map_datasets_path: /Data_PHD/phd22_zhaorui_tan/ssl/pim-generalized-category-discovery-main/npy_feature_maps

gcd_feature_map_datasets_path: /data1/phd21_zhaorui_tan/pim-generalized-category-discovery-with_PL-Reg/npy_feature_maps

cifar10: vit_dino_cifar10_best
cifar100: vit_dino_cifar100_best
imagenet_100: vit_dino_imagenet_100_best

cub: vit_dino_cub_best
scars: vit_dino_scars_best
herbarium: vit_dino_herbarium_19_best